fileVersion: 1
id: "3"
mappingDefinitions:
  RIVERY-STORAGE:
    database: ""
    schema: ""
  SAMPLE:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
  WORK:
    database: SOLUTIONS
    schema: TESTING
name: Production
type: Environment
